Fix gittuf version in dogfood documentation
`gittuf verify-ref v0.4.0` fails. I guess the RSL reset since then?

```
$ gittuf verify-ref --verbose v0.4.0
time=2025-12-02T22:08:49.960+11:00 level=DEBUG msg="Loading Git repository from '.'..."
time=2025-12-02T22:08:49.960+11:00 level=DEBUG msg="Looking for Git binary in PATH..."
time=2025-12-02T22:08:49.960+11:00 level=DEBUG msg="Identifying git directory for repository..."
time=2025-12-02T22:08:49.963+11:00 level=DEBUG msg="Setting git directory for repository to '/home/tom/src/gittuf/.git'..."
time=2025-12-02T22:08:49.963+11:00 level=DEBUG msg="Identifying absolute reference path..."
time=2025-12-02T22:08:49.967+11:00 level=DEBUG msg="Verifying gittuf policies for 'refs/tags/v0.4.0'"
time=2025-12-02T22:08:49.967+11:00 level=DEBUG msg="Loading persistent cache from disk..."
time=2025-12-02T22:08:49.968+11:00 level=DEBUG msg="Persistent cache does not exist"
time=2025-12-02T22:08:49.968+11:00 level=DEBUG msg="Persistent cache not found, using regular RSL searcher..."
time=2025-12-02T22:08:49.968+11:00 level=DEBUG msg="Identifying first RSL entry for 'refs/tags/v0.4.0'..."
Error: unable to find RSL entry
```

```
$ gittuf verify-ref --verbose v0.12.0
time=2025-12-02T22:10:03.772+11:00 level=DEBUG msg="Loading Git repository from '.'..."
time=2025-12-02T22:10:03.772+11:00 level=DEBUG msg="Looking for Git binary in PATH..."
time=2025-12-02T22:10:03.772+11:00 level=DEBUG msg="Identifying git directory for repository..."
time=2025-12-02T22:10:03.775+11:00 level=DEBUG msg="Setting git directory for repository to '/home/tom/src/gittuf/.git'..."
time=2025-12-02T22:10:03.775+11:00 level=DEBUG msg="Identifying absolute reference path..."
time=2025-12-02T22:10:03.780+11:00 level=DEBUG msg="Verifying gittuf policies for 'refs/tags/v0.12.0'"
time=2025-12-02T22:10:03.780+11:00 level=DEBUG msg="Loading persistent cache from disk..."
time=2025-12-02T22:10:03.781+11:00 level=DEBUG msg="Persistent cache does not exist"
time=2025-12-02T22:10:03.781+11:00 level=DEBUG msg="Persistent cache not found, using regular RSL searcher..."
time=2025-12-02T22:10:03.781+11:00 level=DEBUG msg="Identifying first RSL entry for 'refs/tags/v0.12.0'..."
time=2025-12-02T22:10:08.640+11:00 level=DEBUG msg="Identifying latest RSL entry for 'refs/tags/v0.12.0'..."
time=2025-12-02T22:10:08.642+11:00 level=DEBUG msg="Verifying all entries..."
time=2025-12-02T22:10:08.642+11:00 level=DEBUG msg="Loading policy applicable at first entry '0040a38590d908408e730f6cc05cb4d776f45368'..."
time=2025-12-02T22:10:08.644+11:00 level=DEBUG msg="Scanning RSL for search start point using before condition..."
time=2025-12-02T22:10:08.644+11:00 level=DEBUG msg="Found entry '0040a38590d908408e730f6cc05cb4d776f45368' matching before condition..."
time=2025-12-02T22:10:08.644+11:00 level=DEBUG msg="Loading policy at entry 'db004922ef26e725e8986ffb73b80fd0ae3ee945'..."
time=2025-12-02T22:10:08.644+11:00 level=DEBUG msg="Loading persistent cache from disk..."
time=2025-12-02T22:10:08.646+11:00 level=DEBUG msg="Persistent cache does not exist"
time=2025-12-02T22:10:08.646+11:00 level=DEBUG msg="Persistent cache not found, using regular RSL searcher..."
time=2025-12-02T22:10:08.646+11:00 level=DEBUG msg="Finding first policy entry..."
time=2025-12-02T22:10:08.651+11:00 level=DEBUG msg="Requested policy's entry is the same as first policy entry"
time=2025-12-02T22:10:08.658+11:00 level=DEBUG msg="Loading policy for '' from '319238339b0424666b949ab9ccb6c46f6be03a96'..."
time=2025-12-02T22:10:08.671+11:00 level=DEBUG msg="Loaded current repository policy!"
time=2025-12-02T22:10:08.671+11:00 level=DEBUG msg="Trusting root of trust for initial policy 'db004922ef26e725e8986ffb73b80fd0ae3ee945'..."
time=2025-12-02T22:10:08.671+11:00 level=DEBUG msg="Loading attestations applicable at first entry '0040a38590d908408e730f6cc05cb4d776f45368'..."
time=2025-12-02T22:10:08.673+11:00 level=DEBUG msg="Scanning RSL for search start point using before condition..."
time=2025-12-02T22:10:08.673+11:00 level=DEBUG msg="Found entry '0040a38590d908408e730f6cc05cb4d776f45368' matching before condition..."
time=2025-12-02T22:10:08.688+11:00 level=DEBUG msg="Identifying all entries in range..."
time=2025-12-02T22:10:08.689+11:00 level=DEBUG msg="Verifying entry '0040a38590d908408e730f6cc05cb4d776f45368'..."
time=2025-12-02T22:10:08.689+11:00 level=DEBUG msg="Checking if entry is for policy staging reference..."
time=2025-12-02T22:10:08.690+11:00 level=DEBUG msg="Checking if entry is for policy reference..."
time=2025-12-02T22:10:08.690+11:00 level=DEBUG msg="Checking if entry is for attestations reference..."
time=2025-12-02T22:10:08.690+11:00 level=DEBUG msg="Verifying changes..."
time=2025-12-02T22:10:08.690+11:00 level=DEBUG msg="Entry is for a Git tag, using tag verification workflow..."
time=2025-12-02T22:10:08.694+11:00 level=DEBUG msg="Searching for RSL entry for 'refs/tags/v0.12.0' before entry '0040a38590d908408e730f6cc05cb4d776f45368'..."
time=2025-12-02T22:10:08.695+11:00 level=DEBUG msg="Scanning RSL for search start point using before condition..."
time=2025-12-02T22:10:08.696+11:00 level=DEBUG msg="Found entry '0040a38590d908408e730f6cc05cb4d776f45368' matching before condition..."
time=2025-12-02T22:10:08.701+11:00 level=DEBUG msg="Finding reference authorization attestations for 'refs/tags/v0.12.0' from '0000000000000000000000000000000000000000' to 'f2cf979646c6f997c225b735538197b2e810c02d'..."
time=2025-12-02T22:10:08.701+11:00 level=DEBUG msg="Initializing path cache in policy..."
time=2025-12-02T22:10:08.702+11:00 level=DEBUG msg="Verifying signature of Git object with ID '0040a38590d908408e730f6cc05cb4d776f45368'..."
time=2025-12-02T22:10:08.756+11:00 level=DEBUG msg="Public key 'e32941299cb8c0d93dcf27acb83110d012545604' belonging to principal 'adityasaky' successfully used to verify signature of Git object '0040a38590d908408e730f6cc05cb4d776f45368', counting 'adityasaky' towards threshold..."
time=2025-12-02T22:10:08.756+11:00 level=DEBUG msg="Verifying signature of Git object with ID 'adcd85d558bef6d9d1f8eecd8de1708e786ec344'..."
time=2025-12-02T22:10:08.765+11:00 level=DEBUG msg="Public key 'e32941299cb8c0d93dcf27acb83110d012545604' belonging to principal 'adityasaky' successfully used to verify signature of Git object 'adcd85d558bef6d9d1f8eecd8de1708e786ec344', counting 'adityasaky' towards threshold..."
time=2025-12-02T22:10:08.765+11:00 level=DEBUG msg="Verifying if tip of reference matches expected value from RSL..."
time=2025-12-02T22:10:08.767+11:00 level=DEBUG msg="Verification successful!"
```